//! Shared utilities for standalone iterators.
//!
//! Contains the primitive operations used by every iterator in this module:
//!
//! - [`find_line_end`] — locate the end of the current line.
//! - [`count_escape`] — count consecutive escape bytes preceding a position,
//!   used to determine whether a delimiter is escaped (odd count) or not (even).
//! - [`probe_matcher`] / [`find_any_of`] — turn an arbitrary byte predicate
//!   into a `memchr`-family streaming search.
//!
//! All functions operate on raw byte slices.

pub use crate::span::Span;

/// Return the byte offset of the next `eol` byte at or after `from`, or
/// `src.len()` if none is found. This is the exclusive end of the current line.
#[inline(always)]
pub fn find_line_end(src: &[u8], from: usize, eol: u8) -> usize {
    memchr::memchr(eol, &src[from..])
        .map(|i| from + i)
        .unwrap_or(src.len())
}

/// Probe an arbitrary byte predicate over all 256 values and collect the
/// accepted bytes into `buf`.
///
/// Returns `Some(n)` when the predicate accepts at most three distinct bytes —
/// few enough to drive a `memchr`-family streaming search — or `None` when it
/// accepts more, in which case the caller falls back to line-by-line scanning.
/// Runs once per iterator construction; the predicate closures generated by
/// the grammar are pure byte tests, so the probe is exact.
#[inline]
pub fn probe_matcher(matches: impl Fn(u8) -> bool, buf: &mut [u8; 3]) -> Option<usize> {
    let mut n = 0usize;
    for b in 0..=255u8 {
        if matches(b) {
            if n == 3 {
                return None;
            }
            buf[n] = b;
            n += 1;
        }
    }
    Some(n)
}

/// `memchr` over `n` needle bytes (`n <= 3`), dispatched by count.
#[inline(always)]
pub fn find_any_of(needles: &[u8; 3], n: usize, hay: &[u8]) -> Option<usize> {
    match n {
        0 => None,
        1 => memchr::memchr(needles[0], hay),
        2 => memchr::memchr2(needles[0], needles[1], hay),
        _ => memchr::memchr3(needles[0], needles[1], needles[2], hay),
    }
}

/// Count the number of consecutive `escape` bytes immediately preceding `pos`.
///
/// Used to determine whether a delimiter at `pos` is escaped: an odd count
/// means the delimiter is suppressed; an even count (including zero) means it
/// is active.
#[inline(always)]
pub fn count_escape(src: &[u8], pos: usize, escape: u8) -> u32 {
    let mut n = 0u32;
    let mut k = pos;
    while k > 0 && src[k - 1] == escape {
        n += 1;
        k -= 1;
    }
    n
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- find_line_end tests ---

    // 01. Finds the exact index of the newline character when it exists in the slice
    #[test]
    fn test_01_find_line_end_normal() {
        let src = b"abc\ndef";
        assert_eq!(find_line_end(src, 0, b'\n'), 3);
    }

    // 02. Returns the total slice length when the target end-of-line byte is missing
    #[test]
    fn test_02_find_line_end_missing_eol() {
        let src = b"abcdef";
        assert_eq!(find_line_end(src, 0, b'\n'), 6);
    }

    // 03. Correctly scans from a specific middle offset rather than the slice start
    #[test]
    fn test_03_find_line_end_from_offset() {
        let src = b"abc\ndef\n";
        assert_eq!(find_line_end(src, 4, b'\n'), 7);
    }

    // 04. Handles an empty source slice safely by returning zero immediately
    #[test]
    fn test_04_find_line_end_empty_slice() {
        let src = b"";
        assert_eq!(find_line_end(src, 0, b'\n'), 0);
    }

    // 05. Identifies the line end at index zero if the first byte matches the delimiter
    #[test]
    fn test_05_find_line_end_immediate_match() {
        let src = b"\nabc";
        assert_eq!(find_line_end(src, 0, b'\n'), 0);
    }

    // --- probe_matcher / find_any_of tests ---

    // 06. Collects the accepted bytes of a small predicate in ascending order
    #[test]
    fn test_06_probe_matcher_small_set() {
        let mut buf = [0u8; 3];
        let n = probe_matcher(|b| b == b'-' || b == b'*' || b == b'+', &mut buf);
        assert_eq!(n, Some(3));
        assert_eq!(buf, [b'*', b'+', b'-']);
    }

    // 07. Returns None for a predicate accepting more than three bytes
    #[test]
    fn test_07_probe_matcher_large_set() {
        let mut buf = [0u8; 3];
        assert_eq!(probe_matcher(|b| b.is_ascii_digit(), &mut buf), None);
    }

    // 08. An always-false predicate probes to an empty needle set
    #[test]
    fn test_08_probe_matcher_empty_set() {
        let mut buf = [0u8; 3];
        assert_eq!(probe_matcher(|_| false, &mut buf), Some(0));
    }

    // 09. find_any_of dispatches correctly for one, two, and three needles
    #[test]
    fn test_09_find_any_of_dispatch() {
        let hay = b"xxabc";
        assert_eq!(find_any_of(&[b'c', 0, 0], 1, hay), Some(4));
        assert_eq!(find_any_of(&[b'b', b'c', 0], 2, hay), Some(3));
        assert_eq!(find_any_of(b"abc", 3, hay), Some(2));
    }

    // 10. An empty needle set never matches
    #[test]
    fn test_10_find_any_of_empty() {
        assert_eq!(find_any_of(&[0, 0, 0], 0, b"anything"), None);
    }

    // --- count_escape tests ---

    // 11. Returns zero when there are no escape characters preceding the position index
    #[test]
    fn test_11_count_escape_none() {
        let src = b"abc";
        assert_eq!(count_escape(src, 1, b'\\'), 0);
    }

    // 12. Counts a single isolated escape character located right before the target position
    #[test]
    fn test_12_count_escape_single() {
        let src = b"a\\b";
        assert_eq!(count_escape(src, 2, b'\\'), 1);
    }

    // 13. Accumulates multiple sequential escape markers preceding the target index cleanly
    #[test]
    fn test_13_count_escape_multiple() {
        let src = b"a\\\\\\b";
        assert_eq!(count_escape(src, 4, b'\\'), 3);
    }

    // 14. Evaluates to zero immediately when the position parameter points to index zero
    #[test]
    fn test_14_count_escape_at_start_index() {
        let src = b"\\abc";
        assert_eq!(count_escape(src, 0, b'\\'), 0);
    }

    // 15. Discontinues counting when a non-escape character breaks the backwards sequence chain
    #[test]
    fn test_15_count_escape_stopped_by_normal_char() {
        let src = b"x\\\\y";
        assert_eq!(count_escape(src, 3, b'\\'), 2);
    }
}
