//! Standalone element iterators.
//!
//! Each iterator in this module scans a raw byte slice for one specific element
//! kind, independently of any other parsing context. They are the backing
//! implementation for the `find_*` methods generated by [`define_parser!`].
//!
//! # Standalone vs full parse
//!
//! The full parser ([`parse_text!`]) maintains global state across the entire
//! source: open block slots, paragraph boundaries, inline trigger dispatch, and
//! escape context. Standalone iterators carry none of this — each one is a
//! self-contained forward scan over the raw bytes.
//!
//! Consequences:
//!
//! - A standalone iterator **may** yield spans that `parse_text!` would have
//!   suppressed — for example, a delimiter inside a fenced block, or a trigger
//!   byte that was escaped in context.
//! - Span counts from standalone iterators and from full-parse content fields
//!   **can differ by design**. This is not a bug.
//! - Standalone iterators are faster for single-element queries on large sources
//!   because they skip all cross-element bookkeeping.
//! - For rules whose grammar arm declares `parse_inside = false`, a second,
//!   context-aware method is also generated — see [`context`] and
//!   [`context_iter`] — that closes most of this gap at the cost of one extra
//!   sequential pass, shared across every context-aware call.
//!
//! # Iterator types
//!
//! | Type | Grammar rule | Yields |
//! |------|-------------|--------|
//! | [`SymmetricExactIter`] | `symmetric byte { N => field }` | `Span` |
//! | [`AsymmetricExactIter`] | `asymmetric open, close { N => field }` | `Span` |
//! | [`ChainedIter`] | `chained: Type { ... }` | `T` |
//! | [`KvIter`] | `key_value: Type { ... }` | `T` |
//! | [`LineMarkerIter`] | `line(byte, max = N)` | `(T, Span)` |
//! | [`LineUniformIter`] | `line_simple(bytes, min = N)` | `(T, Span)` |
//! | [`FenceIter`] | `fence(byte, min = N)` | `Span` |
//! | [`ContIter`] | `cont(byte)` | `Span` |
//! | [`BlockMarkerIter`] | `block { (pattern) }` | `(T, Span)` |
//! | [`BlockNumberedIter`] | `block { num(...) }` | `(T, Span)` |
//! | [`ContextSymmetricExactIter`] | `symmetric byte { parse_inside = false; N => field }` | `Span` |
//! | [`ContextAsymmetricExactIter`] | `asymmetric open, close { parse_inside = false; N => field }` | `Span` |
//!
//! [`SymmetricExactIter`]: symmetric::SymmetricExactIter
//! [`AsymmetricExactIter`]: asymmetric::AsymmetricExactIter
//! [`ChainedIter`]: chained::ChainedIter
//! [`KvIter`]: key_value::KvIter
//! [`LineMarkerIter`]: line_marker::LineMarkerIter
//! [`LineUniformIter`]: line_uniform::LineUniformIter
//! [`FenceIter`]: fence::FenceIter
//! [`ContIter`]: cont::ContIter
//! [`BlockMarkerIter`]: block_marker::BlockMarkerIter
//! [`BlockNumberedIter`]: block_numbered::BlockNumberedIter
//! [`ContextSymmetricExactIter`]: context_iter::ContextSymmetricExactIter
//! [`ContextAsymmetricExactIter`]: context_iter::ContextAsymmetricExactIter

pub(crate) mod common;

pub mod context;
pub mod context_iter;

pub mod asymmetric;
pub mod block_marker;
pub mod block_numbered;
pub mod chained;
pub mod cont;
pub mod fence;
pub mod key_value;
pub mod line_marker;
pub mod line_uniform;
pub mod symmetric;

/// Emit `find_*` standalone iterator methods for a grammar's rule set.
///
/// # Purpose
///
/// `define_standalone_fns!` is invoked inside the `impl <Name>Parser` block
/// generated by [`define_parser!`]. For each rule in the grammar that supports
/// standalone scanning it emits one `pub fn find_<field>(source: &[u8]) ->
/// impl Iterator` method, wiring the appropriate iterator type with the rule's
/// compile-time parameters.
///
/// For every rule whose grammar arm declares `parse_inside = false` — a
/// *transparent* rule — a second method, `find_context_<field>(source, ctx:
/// &ParseContext)`, is also emitted, plus one `Parser::context(source) ->
/// ParseContext` builder shared by all of them. *Opaque* rules (the ones with
/// `parse_inside = false` themselves — fences, code spans, strings, and so
/// on) get no `find_context_*` variant: they are the source of the context,
/// not a consumer of it.
///
/// The macro is not part of the public API and is called only by the expansion
/// of `define_parser!`. Grammar authors never invoke it directly.
///
/// # Generated methods
///
/// Each rule kind maps to one iterator type and one generated method:
///
/// | DSL rule                                    | Generated method | Iterator                |
/// |---------------------------------------------|------------------|-------------------------|
/// | `symmetric_exact(byte, count)`              | `find_<field>`   | [`SymmetricExactIter`]  |
/// | `asymmetric_exact(open, close, count)`      | `find_<field>`   | [`AsymmetricExactIter`] |
/// | `chained(o1,c1,o2,c2,prefix,Type,pf,ff,sf)` | `find_<field>`   | [`ChainedIter`]         |
/// | `kv(eq, end, allow, Type, kf, vf)`          | `find_<field>`   | [`KvIter`]              |
/// | `line_marker(byte, max, Type, var)`         | `find_<field>`   | [`LineMarkerIter`]      |
/// | `line_uniform([bytes], min, Type, var)`     | `find_<field>`   | [`LineUniformIter`]     |
/// | `fence(byte, min)`                          | `find_<field>`   | [`FenceIter`]           |
/// | `cont(byte)`                                | `find_<field>`   | [`ContIter`]            |
/// | `block_marker([bytes], Type, var)`          | `find_<field>`   | [`BlockMarkerIter`]     |
/// | `block_numbered([ends], Type, nvar, kvar)`  | `find_<field>`   | [`BlockNumberedIter`]   |
///
/// The `sep`, `eol`, `tab`, and `escape` context bytes are forwarded from the
/// grammar's header to each iterator automatically — they do not appear in the
/// individual rule entries.
///
/// # Standalone semantics
///
/// All generated `find_*` methods share the same contract: they scan the source
/// slice independently, without any cross-element context. See the
/// [module-level documentation](self) for a full discussion of how standalone
/// results can differ from the full parse, and how `find_context_*` narrows
/// that gap.
///
/// [`SymmetricExactIter`]: symmetric::SymmetricExactIter
/// [`AsymmetricExactIter`]: asymmetric::AsymmetricExactIter
/// [`ChainedIter`]: chained::ChainedIter
/// [`KvIter`]: key_value::KvIter
/// [`LineMarkerIter`]: line_marker::LineMarkerIter
/// [`LineUniformIter`]: line_uniform::LineUniformIter
/// [`FenceIter`]: fence::FenceIter
/// [`ContIter`]: cont::ContIter
/// [`BlockMarkerIter`]: block_marker::BlockMarkerIter
/// [`BlockNumberedIter`]: block_numbered::BlockNumberedIter
#[doc(hidden)]
#[macro_export]
macro_rules! define_standalone_fns {
    // New-format entry: a `context { ... }` header (emitted by
    // `define_parser!` from the grammar's fence rules and
    // `parse_inside = false` inline rules) precedes the rule list. Emits
    // `context()` alongside the finders.
    (sep=$sep:literal, eol=$eol:literal, tab=$tab:literal, escape=$esc:literal ;
     context { fences [ $( ($fb:literal, $fm:literal) ),* ]
               sym    [ $( ($sb:literal, $sc:literal) ),* ]
               asym   [ $( ($ao:literal, $acl:literal, $an:literal) ),* ] }
     $($rest:tt)*) => {
        /// Build the [`ParseContext`](crate::ParseContext) for `source`:
        /// every fenced block and every `parse_inside = false` inline
        /// construct of this grammar, resolved leftmost-first in one
        /// sequential pass. Feed the result to the `find_context_*` methods.
        pub fn context(source: &[u8]) -> $crate::ParseContext {
            $crate::ParseContext::build(
                source, $eol, $esc, $sep, $tab,
                &[ $( ($fb, $fm as u8) ),* ],
                &[ $( ($sb, $sc as u32) ),* ],
                &[ $( ($ao, $acl, $an as u32) ),* ],
            )
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    // Legacy entry (no context header): finders only, no `context()`.
    (sep=$sep:literal, eol=$eol:literal, tab=$tab:literal, escape=$esc:literal ; $($rest:tt)*) => {
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    // Transparent symmetric rule: context-free finder + context-aware finder.
    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     symmetric_exact($byte:literal, $count:literal, transparent) => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = $crate::span::Span> + '_ {
                $crate::SymmetricExactIter::new(source, $byte, $count, $eol, $esc)
            }
            #[allow(missing_docs)]
            pub fn [<find_context_ $field>]<'s>(
                source: &'s [u8],
                ctx: &'s $crate::ParseContext,
            ) -> impl ::std::iter::Iterator<Item = $crate::span::Span> + 's {
                $crate::ContextSymmetricExactIter::new(source, $byte, $count, $eol, $esc, ctx)
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    // Opaque symmetric rule (`parse_inside = false`): context-free finder
    // only. The rule is itself a context *source* — its own spans coincide
    // with opaque regions, so a context-aware finder for it would be
    // degenerate.
    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     symmetric_exact($byte:literal, $count:literal, opaque) => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = $crate::span::Span> + '_ {
                $crate::SymmetricExactIter::new(source, $byte, $count, $eol, $esc)
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    // Legacy symmetric rule (no opacity marker): behaves as before.
    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     symmetric_exact($byte:literal, $count:literal) => $field:ident ; $($rest:tt)*) => {
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ;
            symmetric_exact($byte, $count, opaque) => $field ; $($rest)* }
    };

    // Transparent asymmetric rule: context-free finder + context-aware finder.
    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     asymmetric_exact($open:literal, $close:literal, $count:literal, transparent) => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = $crate::span::Span> + '_ {
                $crate::AsymmetricExactIter::new(source, $open, $close, $count, $eol, $esc)
            }
            #[allow(missing_docs)]
            pub fn [<find_context_ $field>]<'s>(
                source: &'s [u8],
                ctx: &'s $crate::ParseContext,
            ) -> impl ::std::iter::Iterator<Item = $crate::span::Span> + 's {
                $crate::ContextAsymmetricExactIter::new(source, $open, $close, $count, $eol, $esc, ctx)
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    // Opaque asymmetric rule: context-free finder only (context source).
    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     asymmetric_exact($open:literal, $close:literal, $count:literal, opaque) => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = $crate::span::Span> + '_ {
                $crate::AsymmetricExactIter::new(source, $open, $close, $count, $eol, $esc)
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    // Legacy asymmetric rule (no opacity marker): behaves as before.
    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     asymmetric_exact($open:literal, $close:literal, $count:literal) => $field:ident ; $($rest:tt)*) => {
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ;
            asymmetric_exact($open, $close, $count, opaque) => $field ; $($rest)* }
    };

    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     chained($o1:literal, $c1:literal, $o2:literal, $c2:literal, $prefix:literal,
             $ty:ty, $pf:ident, $ff:ident, $sf:ident) => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = $ty> + '_ {
                $crate::ChainedIter::new(source, $o1, $c1, $o2, $c2, $prefix, $eol, $esc,
                    |$pf, $ff, $sf| $ty { $pf, $ff, $sf })
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     kv($eq:literal, $end:literal, $allow:ident, $ty:ty, $kf:ident, $vf:ident) => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = $ty> + '_ {
                $crate::KvIter::new(source, $eq, $end, $allow, $eol, $sep, $tab,
                    |$kf, $vf| $ty { $kf, $vf })
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     line_marker($byte:literal, $max:literal, $ty:ty, $var:ident) { $($body:tt)* } => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = ($ty, $crate::span::Span)> + '_ {
                $crate::LineMarkerIter::new(source, $byte, $max as u8, $eol, $sep,
                    |$var| $ty { $($body)* })
            }
            #[allow(missing_docs)]
            pub fn [<find_context_ $field>]<'s>(
                source: &'s [u8],
                ctx: &'s $crate::ParseContext,
            ) -> impl ::std::iter::Iterator<Item = ($ty, $crate::span::Span)> + 's {
                let mut _cur = ctx.cursor();
                $crate::LineMarkerIter::new(source, $byte, $max as u8, $eol, $sep,
                    |$var| $ty { $($body)* })
                    .filter(move |(_, s)| !_cur.is_covered(s.start as usize))
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     line_uniform([$($byte:literal),+], $min:literal, $ty:ty, $var:ident) { $($body:tt)* } => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = ($ty, $crate::span::Span)> + '_ {
                $crate::LineUniformIter::new(
                    source, $min as u32, $eol, $sep,
                    |b| ::core::matches!(b, $($byte)|+),
                    |$var| $ty { $($body)* },
                )
            }
            #[allow(missing_docs)]
            pub fn [<find_context_ $field>]<'s>(
                source: &'s [u8],
                ctx: &'s $crate::ParseContext,
            ) -> impl ::std::iter::Iterator<Item = ($ty, $crate::span::Span)> + 's {
                let mut _cur = ctx.cursor();
                $crate::LineUniformIter::new(
                    source, $min as u32, $eol, $sep,
                    |b| ::core::matches!(b, $($byte)|+),
                    |$var| $ty { $($body)* },
                )
                .filter(move |(_, s)| !_cur.is_covered(s.start as usize))
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     fence($byte:literal, $min:literal) => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = $crate::span::Span> + '_ {
                $crate::FenceIter::new(source, $byte, $min as u8, $eol, $sep, $tab)
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     cont($byte:literal) => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = $crate::span::Span> + '_ {
                $crate::ContIter::new(source, $byte, $eol)
            }
            #[allow(missing_docs)]
            pub fn [<find_context_ $field>]<'s>(
                source: &'s [u8],
                ctx: &'s $crate::ParseContext,
            ) -> impl ::std::iter::Iterator<Item = $crate::span::Span> + 's {
                let mut _cur = ctx.cursor();
                $crate::ContIter::new(source, $byte, $eol)
                    .filter(move |s| !_cur.is_covered(s.start as usize))
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     block_marker([$($byte:literal),+], $ty:ty, $var:ident) { $($body:tt)* } => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = ($ty, $crate::span::Span)> + '_ {
                $crate::BlockMarkerIter::new(
                    source, $eol, $sep, $tab,
                    |b| ::core::matches!(b, $($byte)|+),
                    |$var| $ty { $($body)* },
                )
            }
            #[allow(missing_docs)]
            pub fn [<find_context_ $field>]<'s>(
                source: &'s [u8],
                ctx: &'s $crate::ParseContext,
            ) -> impl ::std::iter::Iterator<Item = ($ty, $crate::span::Span)> + 's {
                let mut _cur = ctx.cursor();
                $crate::BlockMarkerIter::new(
                    source, $eol, $sep, $tab,
                    |b| ::core::matches!(b, $($byte)|+),
                    |$var| $ty { $($body)* },
                )
                .filter(move |(_, s)| !_cur.is_covered(s.start as usize))
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;
     block_numbered([$($end:literal),+], $ty:ty, $nvar:ident, $kvar:ident) { $($body:tt)* } => $field:ident ; $($rest:tt)*) => {
        $crate::paste::paste! {
            #[allow(missing_docs)]
            pub fn [<find_ $field>](source: &[u8]) -> impl ::std::iter::Iterator<Item = ($ty, $crate::span::Span)> + '_ {
                $crate::BlockNumberedIter::new(
                    source, $eol, $sep, $tab,
                    |b| ::core::matches!(b, $($end)|+),
                    |$nvar, $kvar| $ty { $($body)* },
                )
            }
            #[allow(missing_docs)]
            pub fn [<find_context_ $field>]<'s>(
                source: &'s [u8],
                ctx: &'s $crate::ParseContext,
            ) -> impl ::std::iter::Iterator<Item = ($ty, $crate::span::Span)> + 's {
                let mut _cur = ctx.cursor();
                $crate::BlockNumberedIter::new(
                    source, $eol, $sep, $tab,
                    |b| ::core::matches!(b, $($end)|+),
                    |$nvar, $kvar| $ty { $($body)* },
                )
                .filter(move |(_, s)| !_cur.is_covered(s.start as usize))
            }
        }
        $crate::define_standalone_fns! { @fns sep=$sep eol=$eol tab=$tab esc=$esc ; $($rest)* }
    };

    (@fns sep=$sep:tt eol=$eol:tt tab=$tab:tt esc=$esc:tt ;) => {};
}
